Add authentication with tunnistamo
City-of-Helsinki/hitas pull request #247
Opened 2023-03-15 14:29 UTC by matti-lamppu

# Hitas Pull Request

# Description

Add the ability to use [tunnistamo](https://github.com/City-of-Helsinki/tunnistamo) as a login method.

Note that this has been tested in local environments only. Hitas does not currently have the necessary client setup
in the actual tunnistamo instance, so this will not work yet in dev or test.

Also, remember to copy the new values from `.env.template` to your own `.env`!

## Pull request checklist

Check the boxes for each DoD item that has been completed:

- **Testing**
  - [x] Changes have been tested
  - [ ] Automatic tests have been added
- **Database**
  - [ ] Database migrations will work in the DEV & TEST environments
  - [ ] initial.json has been updated to work with migrations
  - [ ] Oracle migration has been updated
- **Documentation**
  - [ ] Tooltips have been added in the frontend for all new fields
  - [ ] OpenAPI definitions have been updated
  - [ ] Test instructions have been written for the customer in the appropriate ticket in Jira
  - [ ] Terminology page in Confluence has been updated

## Test plan

- [ ] Follow the instructions in the `backend/README.md` for setting up tunnistamo.

## Tickets

This pull request resolves all or part of the following ticket(s): HT-457, HT-158

2023-03-15 15:51 UTC, matti-lamppu commented
I only tried this with a backend running locally on `localhost:8085`, and seems like it does not work inside the container yet. I'll make some adjustments tomorrow...

2023-03-16 23:14 UTC, ranta requested changes
Please remember to split your commits into smaller, more focused commits. Smaller commits are easier to review and it makes it easier for others to understand the changes that have been made.
For example, this commit added new things, changed some existing code and configs and refactored other code. It should be split into multiple separate commits.

2023-03-17 06:28 UTC, matti-lamppu commented
Ok, should be better separated now 👍

2023-03-24 10:10 UTC, matti-lamppu commented on backend/pyproject.toml
> +social-auth-app-django = "5.0.0"
`social-auth-app-django` version 5.1.0 has some [migration issues](https://github.com/python-social-auth/social-app-django/issues/429) that break our CI, so at the moment this has to be pinned to 5.0.0.

2023-04-03 07:15 UTC, matti-lamppu commented on backend/pyproject.toml
> +social-auth-app-django = "5.0.0"
This has been solved with 5.2.0

2023-04-17 11:58 UTC, ranta approved these changes
🔐

2023-04-18 07:23 UTC, merged