Frontend: Search, modify & add property managers
City-of-Helsinki/hitas pull request #374
Opened 2023-06-16 16:49 UTC by annisassi

# Hitas Pull Request

# Description

New features:
- Search, modify and add property managers in the codes view
- Modify property manager in the apartment details view
Modification:
- "Unmodified" user info to owner modification modal

## Pull request checklist

Check the boxes for each DoD item that has been completed:

- **Testing**
  - [x] Changes have been tested
  - [ ] Automatic tests have been added
- **Database**
  - [ ] Database migrations will work in the DEV & TEST environments
  - [ ] initial.json has been updated to work with migrations
  - [ ] Oracle migration has been updated
- **Documentation**
  - [ ] Tooltips have been added in the frontend for all new fields
  - [ ] OpenAPI definitions have been updated
  - [ ] Test instructions have been written for the customer in the appropriate ticket in Jira
  - [ ] Terminology page in Confluence has been updated

## Test plan

- Modify the property manager info in the apartment details view and check that the validations work as expected and the data updates after modification. 
In the property managers tab in codes view: 
- Search property managers by name and/or email and check you can modify the selected property manager and the data updates after modification.
- Add new property manager and check it is added in the property managers list

## Tickets

This pull request resolves all or part of the following ticket(s): HT-640, HT-644

2023-06-16 19:36 UTC, ranta requested changes

2023-06-19 17:28 UTC, annisassi commented on frontend/src/styles/components/_Codes.sass
> +    margin-top: $spacing-layout-xs
There is a contradiction in the prettier rules as it did not accept the final line break in .sass files (accepts everywhere else), so I had to remove this rule from my IDE.

2023-06-19 17:29 UTC, annisassi commented on frontend/src/app/services.ts
> +    tagTypes: ["HousingCompany", "Apartment", "Index", "Owner", "Manager", "ExternalSaleData", "ThirtyYearRegulation"],
This term was uniform with the "owner" term which is not "PropertyOwner" ;D  Are there any other managers in this context? I changed it anyway...

2023-06-19 17:30 UTC, annisassi commented on frontend/src/app/services.ts
> +            providesTags: (result, error, arg) => [{type: "HousingCompany", id: arg}, {type: "Manager"}],
Added it to PropertyManager tags.

2023-06-19 17:32 UTC, annisassi commented on frontend/src/common/components/ModifyManagerModal.tsx
> +                }
The latter is a good idea. I changed the save button to close the mdoal if no changes are made, as it confuses the user if there is no visible error and still the save button is disabled.

2023-06-19 17:32 UTC, annisassi commented on frontend/src/common/components/ModifyManagerModal.tsx
> +            <Dialog.ActionButtons />
Removed

2023-06-19 17:33 UTC, annisassi commented on frontend/src/features/apartment/ApartmentDetailsPage.tsx
> +    const [manager, setManager] = useState<IPropertyManager | undefined>(undefined);
You are right, it's not a list as I misthought at first :) I changed it.

2023-06-19 17:36 UTC, annisassi commented on frontend/src/features/apartment/ApartmentDetailsPage.tsx
> +                />
I added the property manager modification feature to the housing company page too.

2023-06-19 17:38 UTC, annisassi commented on frontend/src/features/codes/ManagersList.tsx
> +    const [manager, setManager] = useState<IPropertyManager | undefined>(undefined);
The component ManagersList does not exist anymore, as there is now a more generic MutateSearchList component instead.

2023-06-19 17:39 UTC, annisassi commented on frontend/src/features/codes/ManagersList.tsx
> +            />
The ManagersList component does not exist anymore, as there is now a MutateSearchList component instead.

2023-06-20 12:44 UTC, vincit-matu approved these changes
Seems to be working fine, and all the issues Eemeli brought up were addressed. 👍

2023-06-20 13:37 UTC, closed without merging