remove realized acquisition price from housing company model
City-of-Helsinki/hitas pull request #88
Opened 2022-10-10 12:32 UTC by toikarin-vincit

- calculate it automatically, it's now prt of `summary`
 - `acquisition_price` is not an object anymore with two values, it's a simple float value now
 - fix both backend and frontend

2022-10-10 14:44 UTC, ranta requested changes

2022-10-10 14:44 UTC, ranta commented on frontend/src/features/housingCompany/HousingCompanyCreatePage.tsx
> +>>>>>>> b758bda (remove realized acquisition price from housing company model)
Merge conflicts

2022-10-11 05:16 UTC, toikarin-vincit commented on frontend/src/features/housingCompany/HousingCompanyCreatePage.tsx
> +>>>>>>> b758bda (remove realized acquisition price from housing company model)
fixed

2022-10-11 07:30 UTC, ranta approved these changes

2022-10-11 07:33 UTC, merged